/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package FormulariosInternos;

import Objetos.Peaje;
import Objetos.Vehiculos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cymaniatico
 */
public class JiFrmPeaje extends javax.swing.JInternalFrame {

    /**
     * Creates new form JiFrmPeaje
     */
    
    ArrayList<Peaje> registros;
    ArrayList<Vehiculos> listadoVehiculos;
    String placa;
    int perfil;
    
    String[] encabezado = {"Placa","Tipo de Vehiculo", "Fecha", "Valor pagado"};
    public JiFrmPeaje(int perfil) {
        initComponents();
        this.perfil = perfil;
        registros = new ArrayList();
        listadoVehiculos = new ArrayList();
        listadoVehiculos.add(new Vehiculos("Carro", 12000));
        listadoVehiculos.add(new Vehiculos("MiniVan", 25000));
        listadoVehiculos.add(new Vehiculos("Bus", 48000));
        listadoVehiculos.add(new Vehiculos("Camion", 79000));
        txtPlaca.setText("");
        llenarCombo();
        mostrarInfo();
        if(this.perfil != 1){
            scrollRegistros.setVisible(false);
        }
        
        
    }

    public void llenarCombo(){
        comboVehiculo.removeAllItems();
        comboVehiculo.addItem("Seleccione...");
        for (int i = 0; i < listadoVehiculos.size(); i++) {
            Vehiculos item = listadoVehiculos.get(i);
            comboVehiculo.addItem(item.getTipoVehiculo());
        }
    }
    
    public void guardarInfo(){
        if(!txtPlaca.getText().isEmpty() && 
                comboVehiculo.getSelectedIndex()>0){
            int itemSeleccionado = comboVehiculo.getSelectedIndex()-1;
            placa = txtPlaca.getText().toUpperCase();
            String tipo = listadoVehiculos.get(itemSeleccionado)
                    .getTipoVehiculo();
            int valor = listadoVehiculos.get(itemSeleccionado)
                    .getValor();
            registros.add(new Peaje(placa, tipo, valor));
            JOptionPane.showMessageDialog(rootPane, 
                    "Guardado con exito");
            mostrarInfo();
        }else{
            JOptionPane.showMessageDialog(rootPane, 
                    "Faltan campos por completar");
        }
    }
    
    public void mostrarInfo(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(encabezado);
        for (int i = 0; i < registros.size(); i++) {
            modelo.addRow(new Object[]{
                registros.get(i).getPlaca(),
                registros.get(i).getTipo(),
                registros.get(i).getFecha(),
                registros.get(i).getValorCobrado()
            });
        }
        tableRegistros.setModel(modelo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPlaca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboVehiculo = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        scrollRegistros = new javax.swing.JScrollPane();
        tableRegistros = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        txtPlaca.setText("jTextField1");

        jLabel2.setText("Seleccione el tipo de vehiculo");

        comboVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        tableRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollRegistros.setViewportView(tableRegistros);

        jLabel1.setText("Ingrese la placa del vehiculo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollRegistros)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboVehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegistrar)
                        .addGap(0, 205, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        guardarInfo();
    }//GEN-LAST:event_btnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> comboVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane scrollRegistros;
    private javax.swing.JTable tableRegistros;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
